### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by vassilevsky** [AI4Finance-LLC/Elegant-FinRL#3]
Hello :)

I was wondering if this project is ready to use. There is no instruction for installing dependencies and running it.

I opened it because it is the latest one.

**Comment by YangletLiu** [comment]
If you can run PyTorch on your PC, than no more instructions.

**Comment by YangletLiu** [comment]
Currently, one can write Jupyter Notebooks for new tasks. Or, write a Python file, as in the ElegantRL lib.
